In [1]:
import numpy as np

In [2]:
# 1. Create a 5x5 NumPy array filled with normally distributed (i.e. μ = 0,σ = 1)
arr=np.random.normal(0,1,size=(5,5))
print(arr)

[[ 0.49976672  0.36092659 -1.28240038 -0.73418788  2.53918208]
 [ 0.43147391  1.78632608  0.31963655  2.30652922 -0.09030664]
 [-0.15470256 -0.6881398   0.50906459  0.61962139 -0.44732781]
 [ 0.35900533 -0.56515165 -0.1907746  -0.99650698 -0.7976852 ]
 [-0.20684388  0.41090437  0.04233127 -1.17627762  1.19024402]]


In [3]:
# 2. If the value of an entry is greater than 0.09, replace it with its square.Else, replace it with 42.
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i][j]>0.09:
            arr[i][j]=arr[i][j]**2
        else:
            arr[i][j]=42
print(arr)

[[ 0.24976678  0.130268   42.         42.          6.44744565]
 [ 0.18616974  3.19096088  0.10216752  5.32007705 42.        ]
 [42.         42.          0.25914676  0.38393067 42.        ]
 [ 0.12888483 42.         42.         42.         42.        ]
 [42.          0.1688424  42.         42.          1.41668082]]


In [6]:
# 3. Use slicing to print just the fourth column of your array.
print(arr[:,3])

[42.          5.32007705  0.38393067 42.         42.        ]
